"use client";

import { FormEvent, useEffect, useState } from "react";
import PageHeader from "@/components/PageHeader";
import { apiFetch } from "@/lib/api";
import type { Connection, Provider } from "@/lib/types";

const providers:Provider[]=["mock","facebook","instagram","linkedin","whatsapp","youtube","tiktok","x"];
export default function ConnectionsPage(){const [items,setItems]=useState<Connection[]>([]),[show,setShow]=useState(false),[error,setError]=useState("");async function load(){setItems(await apiFetch<Connection[]>("/connections"))}useEffect(()=>{load()},[]);async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setError("");const f=new FormData(e.currentTarget);let metadata={};try{metadata=JSON.parse(String(f.get("metadata_json")||"{}"))}catch{setError("Metadata must be valid JSON");return}try{await apiFetch("/connections",{method:"POST",body:JSON.stringify({provider:f.get("provider"),display_name:f.get("display_name"),external_account_id:f.get("external_account_id"),access_token:f.get("access_token"),refresh_token:f.get("refresh_token"),metadata_json:metadata})});setShow(false);await load()}catch(err){setError(err instanceof Error?err.message:"Connection failed")}}async function toggle(id:string){await apiFetch(`/connections/${id}/toggle`,{method:"POST"});await load()}return <><PageHeader eyebrow="Official account access" title="Social connections" description="Tokens are encrypted in the backend and never returned to the browser." action={<button className="primary-button" onClick={()=>setShow(v=>!v)}>{show?"Close":"Add connection"}</button>}/>{show&&<form className="panel connection-form" onSubmit={submit}><div className="form-grid"><label>Provider<select name="provider">{providers.map(p=><option key={p}>{p}</option>)}</select></label><label>Display name<input name="display_name" required placeholder="Madani Facebook Page"/></label><label>External account ID<input name="external_account_id" required placeholder="Page ID, Phone Number ID or organization URN"/></label><label>Access token<input name="access_token" type="password" autoComplete="off"/></label><label>Refresh token<input name="refresh_token" type="password" autoComplete="off"/></label><label className="span-two">Provider metadata JSON<textarea name="metadata_json" rows={5} defaultValue={'{\n  "page_id": ""\n}'}/></label></div>{error&&<div className="error-box">{error}</div>}<button className="primary-button">Save encrypted connection</button></form>}<section className="connection-grid">{items.map(item=><article className="connection-card" key={item.id}><div className={`connection-logo provider-${item.provider}`}>{item.provider.slice(0,2).toUpperCase()}</div><div><div className="connection-title"><strong>{item.display_name}</strong><span className={item.is_active?"online":"offline"}>{item.is_active?"Active":"Disabled"}</span></div><p>{item.provider} · {item.external_account_id}</p><small>Added {new Date(item.created_at).toLocaleDateString()}</small></div><button onClick={()=>toggle(item.id)}>{item.is_active?"Disable":"Enable"}</button></article>)}</section></>}
