"use client";

import { use, useEffect, useState } from "react";
import PageHeader from "@/components/PageHeader";
import StatusBadge from "@/components/StatusBadge";
import { apiFetch } from "@/lib/api";
import type { Campaign, Connection, SocialPost } from "@/lib/types";

export default function CampaignDetail({params}:{params:Promise<{id:string}>}){
 const {id}=use(params); const [campaign,setCampaign]=useState<Campaign|null>(null); const [connections,setConnections]=useState<Connection[]>([]); const [busy,setBusy]=useState(""); const [error,setError]=useState("");
 async function load(){const [c,x]=await Promise.all([apiFetch<Campaign>(`/campaigns/${id}`),apiFetch<Connection[]>("/connections")]);setCampaign(c);setConnections(x)}
 useEffect(()=>{load()},[id]);
 async function generate(){setBusy("generate");setError("");try{setCampaign(await apiFetch<Campaign>(`/campaigns/${id}/generate`,{method:"POST"}))}catch(e){setError(e instanceof Error?e.message:"Generation failed")}finally{setBusy("")}}
 async function save(post:SocialPost,body:string,title:string,media:string,connection:string,payload:string){setBusy(post.id);try{await apiFetch(`/posts/${post.id}`,{method:"PATCH",body:JSON.stringify({body,title,media_url:media,connection_id:connection||null,provider_payload:JSON.parse(payload||"{}")})});await load()}catch(e){setError(e instanceof Error?e.message:"Save failed")}finally{setBusy("")}}
 async function action(post:SocialPost,type:"approve"|"publish"|"cancel"){setBusy(post.id);try{await apiFetch(`/posts/${post.id}/${type}`,{method:"POST"});await load()}catch(e){setError(e instanceof Error?e.message:"Action failed")}finally{setBusy("")}}
 async function schedule(post:SocialPost,value:string){if(!value)return;setBusy(post.id);try{await apiFetch(`/posts/${post.id}/schedule`,{method:"POST",body:JSON.stringify({scheduled_for:new Date(value).toISOString()})});await load()}catch(e){setError(e instanceof Error?e.message:"Schedule failed")}finally{setBusy("")}}
 if(!campaign)return <div className="screen-loader"><div className="spinner"/><p>Loading campaign</p></div>;
 return <><PageHeader eyebrow={campaign.content_type} title={campaign.name} description={campaign.brief} action={<button className="primary-button" onClick={generate} disabled={busy==="generate"}>{busy==="generate"?"Generating":"Generate all drafts"}</button>}/>{error&&<div className="error-box page-error">{error}</div>}<section className="post-grid">{campaign.posts.map(post=><PostEditor key={post.id} post={post} connections={connections} busy={busy===post.id} onSave={save} onAction={action} onSchedule={schedule}/>)}</section></>;
}

function PostEditor({post,connections,busy,onSave,onAction,onSchedule}:{post:SocialPost;connections:Connection[];busy:boolean;onSave:(p:SocialPost,b:string,t:string,m:string,c:string,j:string)=>void;onAction:(p:SocialPost,t:"approve"|"publish"|"cancel")=>void;onSchedule:(p:SocialPost,v:string)=>void}){
 const [body,setBody]=useState(post.body),[title,setTitle]=useState(post.title),[media,setMedia]=useState(post.media_url),[connection,setConnection]=useState(post.connection_id||""),[payload,setPayload]=useState(JSON.stringify(post.provider_payload||{},null,2)),[uploading,setUploading]=useState(false);useEffect(()=>{setBody(post.body);setTitle(post.title);setMedia(post.media_url);setConnection(post.connection_id||"");setPayload(JSON.stringify(post.provider_payload||{},null,2))},[post]); async function upload(file:File){setUploading(true);try{const form=new FormData();form.append("file",file);const result=await apiFetch<{url:string}>("/media/upload",{method:"POST",body:form});setMedia(result.url)}finally{setUploading(false)}}
 const available=connections.filter(c=>c.provider===post.platform||c.provider==="mock");
 return <article className="post-editor"><div className="post-editor-head"><div><span className="platform-label">{post.platform}</span><StatusBadge status={post.status}/></div>{post.last_error&&<small className="failure-text">{post.last_error}</small>}</div><label>Title<input value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Post content<textarea rows={10} value={body} onChange={e=>setBody(e.target.value)}/></label><label>Media URL<input value={media} onChange={e=>setMedia(e.target.value)} placeholder="Public image or video URL when required"/></label><label>Upload media<input type="file" accept="image/*,video/*" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0])}/><small>{uploading?"Uploading":"The returned public URL will be inserted above."}</small></label><label>Provider payload JSON<textarea rows={5} value={payload} onChange={e=>setPayload(e.target.value)} placeholder="Recipients, privacy level or provider specific settings"/></label><label>Publishing connection<select value={connection} onChange={e=>setConnection(e.target.value)}><option value="">Automatic active connection</option>{available.map(c=><option key={c.id} value={c.id}>{c.display_name} ({c.provider})</option>)}</select></label><div className="visual-note"><strong>Visual idea</strong><p>{post.visual_idea||"Generate content to receive a visual suggestion."}</p></div><div className="post-actions"><button onClick={()=>onSave(post,body,title,media,connection,payload)} disabled={busy}>Save</button><button className="approve" onClick={()=>onAction(post,"approve")} disabled={busy||!body}>Approve</button><input type="datetime-local" onChange={e=>onSchedule(post,e.target.value)} disabled={busy||!["approved","scheduled"].includes(post.status)}/><button className="publish" onClick={()=>onAction(post,"publish")} disabled={busy||!["approved","scheduled","failed"].includes(post.status)}>Publish now</button></div>{post.external_post_url&&<a className="external-link" href={post.external_post_url} target="_blank">Open published post</a>}</article>
}
