"use client";

import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import PageHeader from "@/components/PageHeader";
import { apiFetch } from "@/lib/api";
import type { Campaign, Provider } from "@/lib/types";

const allPlatforms: Provider[]=["facebook","instagram","linkedin","whatsapp","youtube","tiktok","x"];
export default function NewCampaignPage(){
 const router=useRouter(); const [platforms,setPlatforms]=useState<Provider[]>(["facebook","instagram","linkedin","whatsapp"]); const [loading,setLoading]=useState(false); const [error,setError]=useState("");
 function toggle(p:Provider){setPlatforms(v=>v.includes(p)?v.filter(x=>x!==p):[...v,p])}
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);setError("");const form=new FormData(e.currentTarget);try{const campaign=await apiFetch<Campaign>("/campaigns",{method:"POST",body:JSON.stringify({name:form.get("name"),brief:form.get("brief"),content_type:form.get("content_type"),language:form.get("language"),tone:form.get("tone"),audience:form.get("audience"),objective:form.get("objective"),platforms,settings:{website_url:form.get("website_url"),whatsapp_number:form.get("whatsapp_number"),require_approval:true}})});router.push(`/campaigns/${campaign.id}`)}catch(err){setError(err instanceof Error?err.message:"Could not create campaign")}finally{setLoading(false)}}
 return <><PageHeader eyebrow="New content" title="Create campaign" description="Give complete facts once. The AI will adapt them for each selected platform."/><form className="panel form-stack" onSubmit={submit}><div className="form-grid"><label>Campaign name<input name="name" required minLength={3} placeholder="Basic Qaida Lesson 9 promotion"/></label><label>Content type<select name="content_type"><option>Course Promotion</option><option>YouTube Video</option><option>Admissions Campaign</option><option>Parent Notice</option><option>Student Achievement</option><option>Islamic Reminder</option><option>Blog Promotion</option><option>Fee Reminder</option></select></label><label className="span-two">Topic and complete facts<textarea name="brief" required rows={7} placeholder="Include the exact video link, learning points, dates and what action parents should take."/></label><label>Language<select name="language"><option>English</option><option>Roman Urdu</option><option>Urdu</option></select></label><label>Tone<select name="tone"><option>Warm Islamic</option><option>Professional</option><option>Friendly</option><option>Educational</option><option>Persuasive but honest</option><option>Short and direct</option></select></label><label>Audience<select name="audience"><option>Parents and Students</option><option>Parents</option><option>Children</option><option>Adult Learners</option><option>UK Families</option><option>Global Muslim Families</option></select></label><label>Goal<select name="objective"><option>Get enquiries</option><option>Get video views</option><option>Get comments</option><option>Share information</option><option>Get trial registrations</option><option>Get website visits</option></select></label><label>Website URL<input name="website_url" defaultValue="https://madaniislamicacademy.com/"/></label><label>WhatsApp number<input name="whatsapp_number" defaultValue="+44 7480 676283"/></label></div><div><span className="label-title">Platforms</span><div className="platform-picker">{allPlatforms.map(p=><button type="button" key={p} onClick={()=>toggle(p)} className={platforms.includes(p)?"selected":""}>{p}</button>)}</div></div>{error&&<div className="error-box">{error}</div>}<div className="form-actions"><button className="primary-button" disabled={loading||!platforms.length}>{loading?"Creating":"Create campaign"}</button></div></form></>;
}
